---            
- name: Install
  hosts: all
  become: yes
  vars:
    packages: [git,vim,htop,stress]

  tasks:
  - name: update and upgrade debian
    when: ansible_facts['os_family'] == "Debian"
    apt: upgrade=dist update_cache=yes

  - name: install packages
    apt:
      name: '{{ packages }}'
      state: latest
