---
- name: system wide update and upgrade
  hosts: all
  become: yes
  vars:
    packages: [mlocate,net-tools,speedtest-cli,wget,curl,git,vim,htop,stress,python-pip,nano,dnsutils,whois,ufw]
    
  tasks:
  - name: update and upgrade debian
    when: ansible_facts['os_family'] == "Debian"
    apt:
      upgrade: full
      cache_valid_time: 86400
      update_cache: yes
      autoremove: yes

  - name: install packages on debian
    when: ansible_facts['os_family'] == "Debian"
    apt:
      name: '{{ packages }}'
      state: latest

  - name: update and upgrade redhat
    when: ansible_facts['os_family'] == "RedHat"
    dnf:
      name: "*"
      state: latest
      

  - name: install packages on redhat
    when: ansible_facts['distribution'] == "Fedora"
    dnf:
      name: '{{ packages }}'
      state: latest

- name: control install docker
  hosts: control
  become: yes
  vars:
    required: [apt-transport-https,ca-certificates,curl,software-properties-common,virtualenv,python3-pip,python3-setuptools]

  tasks:

  - name: Install required packages for docker
    apt:
      name: '{{ required }}'
      state: latest
      cache_valid_time: 86400
      update_cache: yes

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: Add the user to docker group
    ansible.builtin.user:
      name: vagrant
      groups: docker
      append: yes
